# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "devbox"
    vb.gui = false
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.synced_folder "../", "/shared", disabled: false, type: "virtualbox", id: "vagrant-haproxy"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/play.yml"
  end
end
