---
- name: "Install repos"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "ppa:vbernat/haproxy-1.9"
    - "ppa:ondrej/php"

- name: "Install packages"
  apt:
    state: present
    update_cache: yes
    name: ['haproxy', 'php7.3-cli', 'git', 'php7.3-dom', 'php7.3-xml', 'php7.3-zip', 'php7.3-soap', 'php7.3-xdebug', 'zip', 'unzip']

...
